### ISSUE TITLE
NullPointerException while analysing

### ISSUE THREAD

**Issue by wdigger** [lab313ru/ghidra_amiga_ldr#9]
`Analysis Task: Amiga Library Calls - 
java.lang.NullPointerException
	at amigahunk.AmigaHunkAnalyzer$1.evaluateContext(AmigaHunkAnalyzer.java:221)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:502)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:389)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:188)
	at amigahunk.AmigaHunkAnalyzer.flowConstants(AmigaHunkAnalyzer.java:239)
	at amigahunk.AmigaHunkAnalyzer.added(AmigaHunkAnalyzer.java:159)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:185)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 14.0.2
OS: Mac OS X 10.15.6 x86_64`

I may to attach loaded binary if it's needed.

**Comment by lab313ru** [comment]
Yes, it would be great, to have the binary.

Yury Klushin <notifications@github.com> 16 сентября 2020 г. 23:25:44 написал:

**Comment by wdigger** [comment]
[TheProgram.zip](https://github.com/lab313ru/ghidra_amiga_ldr/files/5238052/TheProgram.zip)
Here it is.

**Comment by lab313ru** [comment]
Fixed in: f581530babd78a512d3f5e26c3ce963161167f49

Check the last release.
